### ISSUE TITLE
BPTL Dshbrd - Packages in Transit table - remove N/A values

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/biospecimen#113]
On the BPTL dashboard, Packages in transit tab, there are cells with N/A. These seem to appear in places where things didn't go quite right on the shipping dashboard.  This table should only show packages that were successfully shipped (maybe this won't be an issue once we fix the problems on the shipping side).

**Comment by Gbarra9** [comment]
The Packages In Transit is displaying the status of two types of shipments from Biospecimen's Shipping Dashboard. 

1. Finalized Collections that were successfully signed from the summary and review tab
2. Boxes in Process from the Shipping's packaging tab

The latter is also being shown inside the current BPTL's Packages in Transit Table. I can filter out and display only the successfully shipped packages.

**Comment by Gbarra9** [comment]
<img width="1043" alt="Screen Shot 2021-12-28 at 1 39 25 PM" src="https://user-images.githubusercontent.com/33293205/147596856-745a686d-a5d9-4fdb-99d1-d4044e9b01b9.png">

**Comment by StephanieWeinstein** [comment]
great, yes, we only want to see the packages that have been successfully shipped.  what you pasted above looks good.  When I test it I still see more than I'm supposed to, but I think you mean this is not yet ready because it is not yet merged?  thanks!

**Comment by Gbarra9** [comment]
> great, yes, we only want to see the packages that have been successfully shipped. what you pasted above looks good. When I test it I still see more than I'm supposed to, but I think you mean this is not yet ready because it is not yet merged? thanks!

That is correct, it wasn't merged to our dev branch at the time.

**Comment by StephanieWeinstein** [comment]
looks good now, thank you!
