### ISSUE TITLE
BPTL Dshbrd - Packages in Transit table -Temperature Monitor information needs to be shown

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/biospecimen#116]
on the BPTL dashboard, on the table of Packages in Transit, we need to add a column that shows which boxes have the temperature monitors.  Norma has said she wants to open those packages last

**Comment by Gbarra9** [comment]
I name the table header Temperature Monitor. The rows are sorted twice. First sort from newest to oldest shipped box collection. Second sort from Temperature Monitor "No" being at the top and Temperature Monitor "Yes" being at the bottom.

<img width="976" alt="Screen Shot 2021-12-28 at 10 56 25 PM" src="https://user-images.githubusercontent.com/33293205/147626172-9cdeecbe-7745-4650-a936-fa8f94255fed.png">
