### ISSUE TITLE
BPTL Home Collection - QC Checks on Kit Assembly page

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#23]
Currently on the Kit Assembly page, the QC checks listed in the Test Case file function correctly.  

We also need the following QC checks to be implemented on the Kit Assembly page:
Supply Kit and Specimen Kit IDs on one line must match
Supply Kit and Specimen Kit IDs must not match IDs on other lines
Collection Cup and Collection Card IDs on one line must match
Collection Cup and Collection Card IDs must not match IDs on other lines

**Comment by Gbarra9** [comment]
**Screenshots of QC Checks**

**Note**: The following QC Checks will show the above alert with information. Please let me know if the alert information needs to be worded differently. I am flexible and willing to change the text to make it easier to read and to understand for the users.


Supply Kit ID and Specimen Kit ID Must Match

<img width="80%" alt="Screen Shot 2021-09-17 at 12 54 34 PM" src="https://user-images.githubusercontent.com/33293205/133826033-3cc43d4a-7e67-455b-976f-6e490aae1c6d.png">
Supply Kit and Specimen Kit IDs must not match IDs on other lines
<img width="80%" alt="Screen Shot 2021-09-17 at 12 45 50 PM" src="https://user-images.githubusercontent.com/33293205/133825214-26c268ed-c1fa-4e7f-a45c-27c853c4d1e6.png">

<img width="80%" alt="Screen Shot 2021-09-17 at 12 46 05 PM" src="https://user-images.githubusercontent.com/33293205/133825262-c48f8b14-e9b9-49bf-9538-31b219d78cb1.png">




Collection Cup and Collection Card IDs on one line must match
<img width="80%" alt="Screen Shot 2021-09-17 at 12 55 21 PM" src="https://user-images.githubusercontent.com/33293205/133826379-6c0f971e-916b-41db-9567-0cd94b7e32c8.png">

Collection Cup and Collection Card IDs must not match IDs on other lines

<img width="80%" alt="Screen Shot 2021-09-17 at 1 04 07 PM" src="https://user-images.githubusercontent.com/33293205/133826990-7ed5541a-612a-4f1f-ae09-52ed592899a0.png">

<img width="80%" alt="Screen Shot 2021-09-17 at 12 55 10 PM" src="https://user-images.githubusercontent.com/33293205/133826316-385c1660-4cbd-430a-8a42-46a7de2349d1.png">

**Comment by wyattks** [comment]
Those will work.  Thank you

**Comment by Gbarra9** [comment]
Thanks for the feedback.
