### ISSUE TITLE
BPTL Home Collection - Participant Selection Status updates

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#24]
On the Participant Selection screen when I use the Select to Print Address function, the participant's status when the Participant Selection is set to Pending in the drop down does not change.  The participant will show up on the Address Printed list but will also remain on the Pending List,

For example: I select Jolyene Cujoh and generate the address file.  I open the file generated and then refresh the dashboard.  Jolyene will remain on the pending list with a status of pending but will now also show up on the Address Printed list with a status of addressPrinted.  Even if I go out of the dashboard and come back in, Jolyene remains in both places.

**Comment by abhinavjonnada82** [comment]
@wyattks The participants we're using are from mock data. The moment we start using actual data, this problem wouldn't happen...

**Comment by wyattks** [comment]
Thanks!
