### ISSUE TITLE
CSV File issues

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#254]
While running some tests on the BTL dashboard, we noticed several issues with the csv file.

1 - Several Collection IDs not received on a day (5/13/2022) showed up in the file as being received on that day.  For instance, Michelle received CXA000043 today (5/13/2022). when she ran the csv report (5-13-2022-BSI-data-export) with a date of 5/13/2022 the following Collection IDs were on the repot in addition to CXA000043;
CXA123423
CXA123421
CXA123422
CXA123425
These IDs were also on a report (csv Data Check) I ran on 5/11/2022.

2 - For CXA000043, Erin entered this from Health Partners, and we are still seeing the undefined data in the report. 

3 - The Biohazard bags and sleeves are showing up on the report.  We do not need these on the report.  Typically they have the 0008 and 0009 sequence numbers.

4 - When I ran my report, I had several Specimens on the report that were not shipped, they are highlighted in an orange/red color.  Under comments I wrote in what the deviation was or if it was marked as missing at the time of shippind.  Several of them had discard deviations where they would not ship and others were marked as missing on the shipping dashboard at the time of shipment.  We have asked Erin to enter in discard deviations and missing tubes into a collection/shipment from HP so we can see what happens.

[5_13_2022-BSI-data-export.csv](https://github.com/episphere/biospecimen/files/8690931/5_13_2022-BSI-data-export.csv)

[csv DAta check.xlsx](https://github.com/episphere/biospecimen/files/8690932/csv.DAta.check.xlsx)

**Comment by abhinavjonnada82** [comment]
[5_18_2022-BSI-data-export (5).csv](https://github.com/episphere/biospecimen/files/8719448/5_18_2022-BSI-data-export.5.csv)

**Comment by abhinavjonnada82** [comment]
[5_18_2022-BSI-data-export (8).csv](https://github.com/episphere/biospecimen/files/8719464/5_18_2022-BSI-data-export.8.csv)

**Comment by wyattks** [comment]
Thank you, Abhinav.  Just one change we need to make.  The SST Tube is now a 8.5 ml volume instead of 10 ml.  So for the 2 SST (Serial #'s 0001 and 0002) tubes we need the following updates:
                        From                                            To 
Vial type          10 mL Serum separator tube       8.5 mL Serum separator tube 
Volume (ml)    10                                                  8.5
All the other defaults can remain the same.
I have update the file listed in issue # 52

**Comment by abhinavjonnada82** [comment]
Orphan Tube:
[5_18_2022-BSI-data-export.csv](https://github.com/episphere/biospecimen/files/8720568/5_18_2022-BSI-data-export.csv)

**Comment by abhinavjonnada82** [comment]
> Thank you, Abhinav. Just one change we need to make. The SST Tube is now a 8.5 ml volume instead of 10 ml. So for the 2 SST (Serial #'s 0001 and 0002) tubes we need the following updates: From To Vial type 10 mL Serum separator tube 8.5 mL Serum separator tube Volume (ml) 10 8.5 All the other defaults can remain the same. I have update the file listed in issue # 52

DONE

**Comment by brotzmanmj** [comment]
@abhinavjonnada82 Did you push the change to 8.5 ml to dev? I don't see it in the CSV file I just generated.
