### ISSUE TITLE
BPTL Home Collection - Participant Selection "All" list does not show pending statuses

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#26]
On the Participant Selection page when the All list is selected, the participants with a status of Pending do not show up on the list.  Participants with the statuses of Address Printed, Assigned, and Shipped show up on the list.  Please make sure the participants with Pending statuses show up on the "All" list.

**Comment by abhinavjonnada82** [comment]
@wyattks 
The reason participants with Kit Status: Pending are not showing up is because we're using mock data. The moment we start using real participant data, then participants with Pending statuses will show up on the "All" list.

**Comment by wyattks** [comment]
Thanks!  That is good to know.
