### ISSUE TITLE
BPTL Home Collection - Collection Cup ID box widen

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/biospecimen#27]
On Kit Assembly page, please make Collection Cup ID box wider so you can see the whole ID when you scan into it

**Comment by Gbarra9** [comment]
Collection Cup ID (BEFORE)

<img width="1139" alt="Screen Shot 2021-09-17 at 1 32 06 PM" src="https://user-images.githubusercontent.com/33293205/133830048-c4194968-ebf8-4848-8ce2-f111158edbdf.png">

Collection Cup ID (UPDATED)
<img width="1147" alt="Screen Shot 2021-09-17 at 1 29 01 PM" src="https://user-images.githubusercontent.com/33293205/133830084-ac0a9c73-03b3-46d5-8fed-74f612ceb6b8.png">

**Note:**
- Increased the input box width for supply kit id, specimen kit id, collection cup id, and collection card id.

**Comment by wyattks** [comment]
Has been fixed.  You can see the entire Id now.
