### ISSUE TITLE
BPTL Dashboard - Menu shading

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/biospecimen#29]
On the top menu where it says Home, Kit Assembly, Participant Selection, Kit Shipment, can you shade the menu option that you're on so it will be clear where you are in the navigation?

**Comment by Gbarra9** [comment]
The Menu Shading Feature has been added to the Home Collection Dashboard. It also had been added to the Receipts Section and Reports Section. https://episphere.github.io/biospecimen/

BPTL Dashboard Page
<img width="800" alt="Screen Shot 2021-10-01 at 9 43 57 AM" src="https://user-images.githubusercontent.com/33293205/135631234-2ca3d807-7271-45c9-9f35-b09c6a81723a.png">

The Home Collection Section Navbar
Kit Assembly
<img width="800" alt="Screen Shot 2021-10-01 at 9 45 51 AM" src="https://user-images.githubusercontent.com/33293205/135631011-f6378414-774b-4c04-87e2-2cd631a2117f.png">
Participant Selection
<img width="800" alt="Screen Shot 2021-10-01 at 9 45 57 AM" src="https://user-images.githubusercontent.com/33293205/135631024-b36324c3-e737-4237-84e2-2894fb9e1595.png">
Kit Shipment
<img width="800" alt="Screen Shot 2021-10-01 at 9 46 02 AM" src="https://user-images.githubusercontent.com/33293205/135631040-6ada7d7f-3b92-4b9b-873c-a61e2d029edf.png">

The Receipts Section Navbar

Packages In Transit
<img width="800" alt="Screen Shot 2021-10-01 at 9 53 31 AM" src="https://user-images.githubusercontent.com/33293205/135632245-b81db297-1bd0-457e-8b51-8e36957d9ee2.png">

Package Receipt
<img width="800" alt="Screen Shot 2021-10-01 at 9 53 37 AM" src="https://user-images.githubusercontent.com/33293205/135632286-648ff934-d090-48b2-bea5-2c1717caf9ee.png">

The Reports Navbar

Reports
<img width="992" alt="Screen Shot 2021-10-01 at 9 54 08 AM" src="https://user-images.githubusercontent.com/33293205/135632395-4c5a6efe-f792-46b3-b536-54861167e857.png">

**Comment by HopkinsDC** [comment]
Change made successfully
