### ISSUE TITLE
BPTL Home Collection - Supply Kit ID not showing whole field

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/biospecimen#34]
On the Assigned Kits page, can we get the Supply Kit ID not to wrap but to show the whole field on one line? Otherwise it's not apparent that there is a space within the ID. 

Related to this, after I click on Edit, it doesn't show me the whole Supply Kit ID in the editable field (maybe because it's wrapping?) Will widening the field fix this?

**Comment by Gbarra9** [comment]
Current Table:

<img width="800" alt="Screen Shot 2021-10-05 at 11 43 25 AM" src="https://user-images.githubusercontent.com/33293205/136057131-c9f19851-8ed9-4feb-8997-764adcfe3aaf.png">

<img width="800" alt="Screen Shot 2021-10-05 at 11 43 37 AM" src="https://user-images.githubusercontent.com/33293205/136058252-2529baf8-db1d-4d20-a51f-de9ade10aa67.png">


Changes Made (In Progress):

<img width="800" alt="Screen Shot 2021-10-05 at 11 44 09 AM" src="https://user-images.githubusercontent.com/33293205/136058743-06e7497b-b622-4df3-86f9-a1695474f9b5.png">
Note: Decrease font size of table cell text content.
<img width="800" alt="Screen Shot 2021-10-05 at 11 44 20 AM" src="https://user-images.githubusercontent.com/33293205/136058758-b84f773a-e86c-4a8b-a0b5-2a2cf8457721.png">
Note: When the user presses the Edit Button, two fields appear for a user to edit. 



The Changes: 
- Decrease width of Supply Kit ID's input field to remove extra space, given Supply Kit ID has to be 9 characters. 
- Increase width of USPS tracking number's input field




> On the Assigned Kits page, can we get the Supply Kit ID not to wrap but to show the whole field on one line? Otherwise it's not apparent that there is a space within the ID.

I am having trouble replicating or seeing the wrapping issue for Supply Kit ID. 
Questions:

- I may be misunderstanding but for confirmation is the Supply Kit ID wrapping issue the "Supply Kit ID" header or the actual value (Ex. CON000300) below? 
- Is it possible to provide a screenshot?

> 
> Related to this, after I click on Edit, it doesn't show me the whole Supply Kit ID in the editable field (maybe because it's wrapping?) Will widening the field fix this?

Questions:

- I am having trouble replicating the Supply Kit ID editable field issue.
- Is it possible to provide a screenshot?

Thank you for the feedback and let me know if you have any questions.

**Comment by brotzmanmj** [comment]
The Supply Kit ID looks fine now, it shows all 9 digits.
