### ISSUE TITLE
Chicago - csv file issue

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#349]
Chicago shipped a collection on Friday that was processed Saturday by BPTL.  In the shipment was CXA002228.  A urine sample was not collected and was not on the manifest.  However, CXA002228 0006 (Urine Tube) showed up on the csv file.  See the last row in the attached file.
[BPTL REceipt 7-23-2022.csv](https://github.com/episphere/biospecimen/files/9183520/BPTL.REceipt.7-23-2022.csv)

**Comment by wyattks** [comment]
Michelle might has found the issue:  Chicago marked the urine tube as Collected on the dashboard. And then they marked it with a Deviation = Yes, and the selected Deviation = Other and in the Deviation Notes they wrote 'could not collect'. So the CSV file was correct, but the data are not entered as we would want Chicago to enter it. They should have recorded the urine as Not Collected and given the reason not collected.

Also the SOP instructs site to mark a tube as discard if they mistakenly mark it as collected and put a reason in of why it is a discard. Chicago did not appear to follow this procedure.

**Comment by Davinkjohnson** [comment]
@wyattks does this mean we should have this "on hold" for now then? (since there's nothing technically we can do to resolve that, and the system acted as intended.)

**Comment by wyattks** [comment]
Yes I will put it on hold.  We think the current update will also take care of the issue as the csv will be based on what is shipped.
