### ISSUE TITLE
BPTL Dashboard receipt issue on 8/24/2022

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#386]
Heather wrote: "We encountered a pretty big dashboard issue today, where all of the packages we “received” were not actually received by the dashboard and are still appearing in the Packages in Transit tab.  We received everything as we normally would, and noticed today the dashboard had been updated with a confirm receipt pop-up which we clicked ok on.  The page refreshed and we continued on with receipt of the next package.  Once done receiving all 6 packages for today, they were still in the Packages in Transit list, and the .csv file for 8/24/22 contained no samples.  Could someone look into this for us?
We were able to add the samples to an incoming batch in BSI by scanning the tubes and adding info from the manifests, but we will not be able to commit any of these to BSI without the .csv file which contains the subject ID and date/time drawn.  Just let us know how to proceed with re-receiving these once the issue is resolved."

Please look into.  We did not encounter these issues during testing.

**Comment by abhinavjonnada82** [comment]
Issue Resolved #387
