### ISSUE TITLE
Add warning if package conditions are not selected

### ISSUE THREAD

**Issue by StephanieWeinstein** [episphere/biospecimen#413]
Norma has noticed that when they try to scroll to the bottom of their dashboard screen to save an entry, this can cause the condition selected to scroll to a different option if they had not clicked outside of the field before scrolling.  Can you add a warning when they save the entry if package conditions are not selected?  Otherwise the entry gets saved with the conditions as "undefined".  thank you!

**Comment by Davinkjohnson** [comment]
track this in #414
