### ISSUE TITLE
BPTL Button not working in BPTL Welcome screen

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#423]
In the production environment, the BPTL button on the welcome screen for the BPTL staff does not work.  If they press it the blue button in the middle of  the screen, it does not take them to the dashboard.  If they use the tab at the top, they can get to the dashboard.  It seems to be just an issue for the BPTL staff.  I am able to use the button.

[BPTL Button Issue.docx](https://github.com/episphere/biospecimen/files/9802508/BPTL.Button.Issue.docx)

**Comment by anthonypetersen** [comment]
bug fix pushed to dev/stage/prod

**Comment by Davinkjohnson** [comment]
Confirmed this AM to be workin in Prod. Closing.
