### ISSUE TITLE
Need a BPTL Collection ID Search

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#426]
We need a search where BPTL can Type in/Scan in a Collection ID, the results returned would be the information located on the "Review Collection Data Entry" screen from the clinical and research dashboards (See Attached).  

The Participant Name would NOT need to be displayed.
The Participant Connect ID and Collection ID would need to be displayed.
All Deviations and Comments would need to be displayed.
A "Return to Search" button is needed on the screen.  This would return the user back to the search BPTL Collection ID search Screen

The search should be located on the BPTL Reports page.  It can look the same as the Collection Search screen on the clinical and research dashboards.
 
[BPTL Collection ID Search Return.docx](https://github.com/episphere/biospecimen/files/9840869/BPTL.Collection.ID.Search.Return.docx)

[BPTL Collection Search Screen.docx](https://github.com/episphere/biospecimen/files/9840870/BPTL.Collection.Search.Screen.docx)

**Comment by anthonypetersen** [comment]
* Fields should not be editable when viewing this page

**Comment by Davinkjohnson** [comment]
This can wait for Abhinav's return

**Comment by abhinavjonnada82** [comment]
Working on it.

**Comment by abhinavjonnada82** [comment]
Test cases available here:
https://github.com/episphere/biospecimen/pull/536#issue-1736706464

**Comment by wyattks** [comment]
Working in Stage.  Chris confirmed

**Comment by wyattks** [comment]
Ready for Production

**Comment by wyattks** [comment]
Works well in Stage.  Ready for Production.

**Comment by abhinavjonnada82** [comment]
Deployed to prod!
