### ISSUE TITLE
BUG: Package Received Date doesn't autopopulate

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/biospecimen#484]
**_Description_**:
**Current Behavior:** When user tries to scan packages in Package Receipt. The Date Received doesn't auto-populate & the user has to manually enter date upon each scan.

**Default Behavior:** Upon Package Receipt screen load, the Date Received input date field should auto-populate with current date.

**Steps to recreate:**
-> Open the Package receipt page on dev & open console tab
-> Warning & error message on console tab upon Package receipt page load:
![image001](https://user-images.githubusercontent.com/30497847/220955859-400ee5a6-c5c0-4f8c-b21a-13710eafa35a.png)

![SnipImage](https://user-images.githubusercontent.com/30497847/220955115-7ed2780d-6c04-44e6-a509-9a4ae57d4d6c.JPG)

**Comment by wyattks** [comment]
Works in Dev
