### ISSUE TITLE
Update Clinical CSV file for Henry Ford Clinical collections

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#497]
Place Holder

Update the clinical csv to include Henry Ford and Health Partner Clinical collections.
Details to come

**Comment by wyattks** [comment]
Need to add clinical collection for Henry Ford to the csv file. Below are the vial details
Sample Collection Center = Henry Ford
Vial Types:

Collection Type	Site	                Serial #	Vial Type	                                Additive/Preservative	Material Type	Volume (ml)
Clinical	                Henry Ford	0001	10 mL Serum separator tube	SST	                                Serum	        10
Clinical	                Henry Ford	0002	10 mL Serum separator tube	SST	                                Serum	        10
Clinical	                Henry Ford	0003	10 ml Vacutainer              	Lithium Heparin	        Whole Blood	10
Clinical	                Henry Ford	0004	10 ml Vacutainer	                EDTA	                        Whole Blood	10
Clinical	                Henry Ford	0005	6 ml Vacutainer	                ACD	                                Whole Blood	 6
Clinical	                Henry Ford	0006	10 ml Vacutainer	                No Additive	                Urine	        10

**Comment by Davinkjohnson** [comment]
Please create separate issue for Health Partners Updates.

Abhinav beginning to work on this this week
