### ISSUE TITLE
Fix Format for cells under the "Tracking Number" column of the In Transit csv file

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#502]
In the In Transit csv file, tracking numbers that show up in the "Tracking number" column are in a general format.  They appear in the file as "6.35214E+11" instead of "635213586245".
Please fix the format to a number format with no decimal places.
Current workaround will be to fix after the file is run but would be good to have it be in the correct format when the file is run.

**Comment by abhinavjonnada82** [comment]
This issue is specific to Microsoft Excel. The column on Tracking Number needs to be expanded to view the complete the number.

**Comment by StephanieWeinstein** [comment]
I just tried it. Expanding the column does not fix the formatting, but you can go in and change the column format from "general" to "number" and then it looks ok.  But that is definitely a pain!  Is there a way to default that at least to numeric, which might help?

**Comment by Davinkjohnson** [comment]
@abhinavjonnada82 will try saving these tracking numbers as strings to see whether this resolves the Excel issue.

**Comment by abhinavjonnada82** [comment]
https://drive.google.com/file/d/1qOG7ZQ7yIuc2tZpi1-oFIM1r07n1HPkI/view?usp=sharing

This should help fix the truncation problem & I'll look for a permanent solution ASAP.

**Comment by Davinkjohnson** [comment]
Next solution:
Have Shipping dashboard output the file as an Excel file (xlsx) with properly formatted columns. Then Norma's team can do "save as" a CSV for the BSI upload.

**Comment by abhinavjonnada82** [comment]
Test cases available here:
https://github.com/episphere/biospecimen/pull/549#issue-1783064612

**Comment by wyattks** [comment]
The dix worked when I tried it in an incognito window and selected .xlsx.

**Comment by wyattks** [comment]
Works correctly i Stage.  Ready for Production

**Comment by abhinavjonnada82** [comment]
Looks good in prod!
