### ISSUE TITLE
Add Material Type to In Transit CSV FIle

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#535]
Please add the Material type for each sample to the In Transit CSV file.

**Comment by Davinkjohnson** [comment]
Material type is already in the other CSV file, please add it to the In - Transit file.

**Comment by abhinavjonnada82** [comment]
Sample in-transit CSV
[6_9_2023-in-transit-data-export (1).csv](https://github.com/episphere/biospecimen/files/11709071/6_9_2023-in-transit-data-export.1.csv)

**Comment by wyattks** [comment]
Looks great. Please move to dev dashboard.

**Comment by wyattks** [comment]
Working in Stage.  Andrea confirmed. Ready for Production

**Comment by wyattks** [comment]
Works in Prod
