### ISSUE TITLE
Change Whole Bl to WHOLE BL in Receipted CSV File

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#550]
With the last prod push, on the Receipted CSV File the material type for Whole Blood was changed from "WHOLE BL" to "Whole Bl".  Please change it back to "WHOLE BL".  BSI is picky and wants it in all caps!

**Comment by wyattks** [comment]
@abhinavjonnada82 I just tried this in Dev in an incognito window and it still shows up as "Whole Bl" in the receipt CSV file.  Let me know when I can try again.  Thanks!

**Comment by abhinavjonnada82** [comment]
[2023-07-18-BSI-data-export.csv](https://github.com/episphere/biospecimen/files/12084154/2023-07-18-BSI-data-export.1.csv)

**Comment by wyattks** [comment]
That file is correct.  Is this in dev?

**Comment by abhinavjonnada82** [comment]
yes

**Comment by wyattks** [comment]
Verified it works in dev.  Ready for stage

**Comment by wyattks** [comment]
Works correctly in Stage.  Ready for Production

**Comment by abhinavjonnada82** [comment]
Deployed to prod!
