### ISSUE TITLE
Change Whole Bl to WHOLE BL in "In Trqansit" CSV File

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#561]
Noticed this also happened in the In Transit file as well: 
With the last prod push, on the In Transit CSV File the material type for Whole Blood was changed from "WHOLE BL" to "Whole Bl". Please change it back to "WHOLE BL". BSI is picky and wants it in all caps!

**Comment by abhinavjonnada82** [comment]
ISSUE HAS BEEN RESOLVED. CONFIRMED BY @HopkinsDC .
