### ISSUE TITLE
Rename "Sequence #" to "Sequence" in the Receipt csv file

### ISSUE THREAD

**Issue by wyattks** [episphere/biospecimen#563]
In the column headers of the recipt csv file, pleae rename the column label "Sequence #" to "Sequence".
This will help with the BSI upload of the document.
![image](https://github.com/episphere/biospecimen/assets/64605220/78b38c24-1d3a-4b29-977d-be7bcf6eaf6b)

**Comment by abhinavjonnada82** [comment]
![Screenshot 2023-08-16 at 4 57 12 PM](https://github.com/episphere/biospecimen/assets/30497847/c5c085ab-e4fb-4f59-a86b-cec202ea2d0d)
